Upgrade Morpho #1
morpho-org/morpho-optimizers pull request #1554
Opened 2022-12-09 08:24 UTC by Rubilmax

# Pull Request

Fixes #1517 

Before merging this PR:
- [x] Merge https://github.com/morpho-dao/morpho-data-structures/pull/108
- [x] Update `lib/morpho-data-structures` submodule

2023-01-17 15:47 UTC, pakim249CAL approved these changes

2023-01-17 15:51 UTC, MerlinEgalite approved these changes

2023-01-18 14:26 UTC, MathisGD approved these changes
LGTM, optional changes:

2023-01-18 14:26 UTC, MathisGD commented on src/compound/InterestRatesManager.sol
>          Types.LastPoolIndexes storage poolIndexes = lastPoolIndexes[_poolToken];
Misleading, as we use `poolSupplyIndex` and `poolBorrowIndex` for the current ones
```suggestion
        Types.LastPoolIndexes storage lastPoolIndexes = lastPoolIndexes[_poolToken];
```

2023-01-24 15:06 UTC, MerlinEgalite requested changes
The last steps described in the PR seems not to have been done

2023-02-12 16:08 UTC, MerlinEgalite approved these changes

2023-03-06 16:11 UTC, julien-devatom commented on README.md
> +- [Morpho Developers Documentation](https://developers.morpho.xyz)
You can also add a desc on how to autogen the developers docs, if needed
To serve it locally:
```
forge doc --build --serve --port 4000
```

2023-03-19 17:53 UTC, MathisGD submitted a review, later dismissed

2023-03-20 09:07 UTC, MerlinEgalite approved these changes

2023-03-20 09:15 UTC, MathisGD approved these changes

2023-03-20 10:05 UTC, merged